
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Change
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: Fixes
      labels:
        - bug fix
